apiVersion: v1
kind: Template
metadata:
  name: ext-test
  annotations:
    description: "Nginx test"
    iconClass: "icon-nginx"
    tags: "latest"
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: ext-test
  spec:
    containers:
      image: dso.ext-test:latest
      name: nginx
      ports:
      - containerPort: 80
        protocol: TCP